--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/12/2019 13:40:38
-- Server version: 8.0.18
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE aguiarsvendasbd;

--
-- Drop table `clientes`
--
DROP TABLE IF EXISTS clientes;

--
-- Drop table `itens`
--
DROP TABLE IF EXISTS itens;

--
-- Drop table `pedidos`
--
DROP TABLE IF EXISTS pedidos;

--
-- Drop table `produtos`
--
DROP TABLE IF EXISTS produtos;

--
-- Drop table `usuarios`
--
DROP TABLE IF EXISTS usuarios;

--
-- Set default database
--
USE aguiarsvendasbd;

--
-- Create table `usuarios`
--
CREATE TABLE usuarios (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  user_nome VARCHAR(100) DEFAULT NULL,
  user_nome_completo VARCHAR(100) DEFAULT NULL,
  user_senha VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `produtos`
--
CREATE TABLE produtos (
  pro_id INT(11) NOT NULL AUTO_INCREMENT,
  pro_nome VARCHAR(100) DEFAULT NULL,
  pro_barra VARCHAR(100) DEFAULT NULL,
  pro_ref VARCHAR(100) DEFAULT NULL,
  pro_custo DOUBLE(9, 2) DEFAULT 0.00,
  pro_preco DOUBLE(9, 2) DEFAULT 0.00,
  pro_preco_prazo DOUBLE(9, 2) DEFAULT 0.00,
  pro_estoque INT(11) DEFAULT NULL,
  PRIMARY KEY (pro_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `pedidos`
--
CREATE TABLE pedidos (
  ped_id INT(11) NOT NULL AUTO_INCREMENT,
  ped_date DATE DEFAULT NULL,
  ped_codigo VARCHAR(50) DEFAULT NULL,
  ped_cliente INT(11) DEFAULT NULL,
  ped_usuario INT(11) DEFAULT NULL,
  ped_forma_pag INT(11) DEFAULT NULL,
  ped_fechado ENUM('SIM,NAO') DEFAULT NULL,
  ped_faturado ENUM('SIM,NAO') DEFAULT NULL,
  PRIMARY KEY (ped_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `itens`
--
CREATE TABLE itens (
  iten_id INT(11) NOT NULL AUTO_INCREMENT,
  iten_produto INT(11) DEFAULT NULL,
  iten_qtd INT(11) DEFAULT NULL,
  iten_pedido VARCHAR(50) DEFAULT NULL,
  iten_preco DOUBLE(9, 2) DEFAULT 0.00,
  iten_preco_prazo DOUBLE(9, 2) DEFAULT NULL,
  PRIMARY KEY (iten_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `clientes`
--
CREATE TABLE clientes (
  cli_id INT(11) NOT NULL AUTO_INCREMENT,
  cli_nome VARCHAR(100) DEFAULT NULL,
  cli_endereco VARCHAR(100) DEFAULT NULL,
  cli_numero VARCHAR(20) DEFAULT NULL,
  cli_bairro VARCHAR(50) DEFAULT NULL,
  cli_cidade VARCHAR(50) DEFAULT NULL,
  cli_fone VARCHAR(20) DEFAULT NULL,
  cli_celular VARCHAR(20) DEFAULT NULL,
  cli_rg VARCHAR(20) DEFAULT NULL,
  cli_cpf VARCHAR(20) DEFAULT NULL,
  cli_profissao VARCHAR(50) DEFAULT NULL,
  cli_data_nasc DATE DEFAULT NULL,
  PRIMARY KEY (cli_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table usuarios
--
-- Table aguiarsvendasbd.usuarios does not contain any data (it is empty)

-- 
-- Dumping data for table produtos
--
-- Table aguiarsvendasbd.produtos does not contain any data (it is empty)

-- 
-- Dumping data for table pedidos
--
-- Table aguiarsvendasbd.pedidos does not contain any data (it is empty)

-- 
-- Dumping data for table itens
--
-- Table aguiarsvendasbd.itens does not contain any data (it is empty)

-- 
-- Dumping data for table clientes
--
-- Table aguiarsvendasbd.clientes does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;